### ISSUE TITLE
OSX version 0.1.2 SHA mismatch

### ISSUE THREAD

**Issue by miltieIV2** [dutchcoders/cloudman#11]
$ brew reinstall cloudman
==> Downloading https://github.com/dutchcoders/cloudman/releases/download/0.1.2/cloudman-0.1.2-x86_64-apple-darwin.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/269740202/92be9300-bb8c-11ea-8eae-9a63d8223cad?X-Amz-Algorithm=AW
Error: SHA256 mismatch
Expected: 15e9f06e0a2393f65c0a884849532687fb9a1ced7940f25cb74069a743387ae8
  Actual: 2a71e5f9fed2a4fe3289a49624c826b9738485ca085ca9402fcf65315524bd6e
 Archive: /Users/johnmilton/Library/Caches/Homebrew/downloads/20f7ff8400a9aef4887e7c949fba2952b9ab907a35c77a47e837251bdad30207--cloudman-0.1.2-x86_64-apple-darwin.tar.gz

**Comment by nl5887** [comment]
Created 0.1.3 this afternoon, could you retry with latest version?

**Comment by miltieIV2** [comment]
yessir, that fixed it.

**Comment by nl5887** [comment]
perfect!
