### ISSUE TITLE
Trying to filter the list causes a panic

### ISSUE THREAD

**Issue by rothgar** [dutchcoders/cloudman#13]
![image](https://user-images.githubusercontent.com/371796/89564878-86080d00-d7d2-11ea-9a98-d660ed348123.png)
Using F3 or F4 and trying to type any key crashes the application.

**Comment by nl5887** [comment]
Does your list contain an instance without a name (tag)?

**Comment by nl5887** [comment]
Should be fixed in release 0.1.4. Currently building.

**Comment by rothgar** [comment]
Yes I had instances without names. Thanks!
