### ISSUE TITLE
Update Cargo.lock file?

### ISSUE THREAD

**Issue by herbygillot** [dutchcoders/cloudman#18]
The lock file in the `0.1.7` release still seems to be for `0.1.6`...

**Comment by nl5887** [comment]
Thanks @herbygillot, just pushed commit 800a5e0272d0604e66b5d4f7dea5f364aee67bb1, updating the lock file.

**Comment by nl5887** [comment]
and thanks for the [MacPort](https://ports.macports.org/port/cloudman/summary) of Cloudman.

**Comment by herbygillot** [comment]
Thank you @nl5887

**Comment by herbygillot** [comment]
And also we could add MacPorts install instructions to the README if you want. 

MacPorts install instructions for cloudman are:

```
sudo port selfupdate
sudo port install cloudman
```

If you really want to have a single line instruction, then `sudo port install cloudman` will do.

**Comment by nl5887** [comment]
Thanks! Added to the README:

https://github.com/dutchcoders/cloudman/blob/master/README.md#macports

**Comment by herbygillot** [comment]
Ok great, much appreciated.
