### ISSUE TITLE
The Linuxbrew installed binary is not executable

### ISSUE THREAD

**Issue by miltieIV2** [dutchcoders/cloudman#3]
$ cloudman --profile=myprofile
-bash: /home/linuxbrew/.linuxbrew/bin/cloudman: Permission denied

$ ls -l /home/linuxbrew/.linuxbrew/bin/../Cellar/cloudman/0.1.1/bin/cloudman
-r--r--r-- 1 john.milton users 6590536 Jun 16 11:28 /home/linuxbrew/.linuxbrew/bin/../Cellar/cloudman/0.1.1/bin/cloudman

$ chmod a+x /home/linuxbrew/.linuxbrew/bin/../Cellar/cloudman/0.1.1/bin/cloudman
$ cloudman --profile=myprofile
-bash: /home/linuxbrew/.linuxbrew/bin/cloudman: cannot execute binary file: Exec format error

And it's not the right executable:
$ file /home/linuxbrew/.linuxbrew/bin/../Cellar/cloudman/0.1.1/bin/cloudman
/home/linuxbrew/.linuxbrew/bin/../Cellar/cloudman/0.1.1/bin/cloudman: Mach-O 64-bit x86_64 executable

**Comment by rothgar** [comment]
I added a PR to support linuxbrew here https://github.com/dutchcoders/homebrew-cloudman/pull/1

**Comment by nl5887** [comment]
Should by fixed by https://github.com/dutchcoders/homebrew-cloudman/pull/1. Please let me know if you still have issues.
