### ISSUE TITLE
Use environment variables for credentials

### ISSUE THREAD

**Issue by enkov** [dutchcoders/cloudman#7]
Hello!
It would be great if we can use environment variables for credentials [aws-envvars](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).
Me and my team using [aws-vault](https://github.com/99designs/aws-vault) to provide credentials to all tools we use.

**Comment by nl5887** [comment]
Version 0.1.3 (https://github.com/dutchcoders/cloudman/releases/tag/0.1.3) will have an extra argument `--use-env` which will use credentials from environments variables.
